### ISSUE TITLE
Question: LOLBAS YAML Property of MITRE Technique ID Aligned to V6 or newer Matrix Versions

### ISSUE THREAD

**Issue by dfirence** [LOLBAS-Project/LOLBAS#103]
Hello

Will this awesome project be updating soon the technique ID field to distinguish if it is mapped to V6 (legacy) or V7 (current) of the ATT&CK Enterprise matrix?

I was looking at your repo for **MpCmdRun**, and I noticed one of the cited techniques is **T1105**

<br/>

You can see below the tool I am using allows for querying both the **enterprise-legacy** and current version of the enterprise matrix.

 I just wanted to integrate your project into the tool I am using and need to know how to reliably afford myself and everyone using my tool an accurate representation of which version of the matrix a technique cited in your repo for the LOLBAS is intended for.

Happy to help too :)

<br/>

![A46FC4D5-C3FD-4B02-AED4-BCA7A1F5DD82](https://user-images.githubusercontent.com/11415591/97253440-ccbe3f80-17e2-11eb-98c2-8f1a5b09f2cc.jpeg)

<br/>

![71F1408D-121E-4F55-B843-DEECABBBFDA5](https://user-images.githubusercontent.com/11415591/97253293-6d602f80-17e2-11eb-9a7e-7cb72fbad60c.jpeg)

**Comment by wietze** [comment]
Mapping updates using the latest version of ATT&CK (v10 at the time of writing) are made in #170. There may be more opportunities for updating existing entries to more specific (sub-)techniques, if you spot any, please open a PR! :slightly_smiling_face:

**Comment by wietze** [comment]
(your tool looks cool btw, I see you have made it public at [dfirence/mitre-assistant](https://github.com/dfirence/mitre-assistant)! keep up the good work :+1: )
