### ISSUE TITLE
Mitre Sub-techniques

### ISSUE THREAD

**Issue by itpropaul** [LOLBAS-Project/LOLBAS#113]
What are thoughts on people doing pull requests to update the yml files to specific Mitre sub-techniques when they're relevant?

For example, in At.yml, update this:
MitreID: T1053
MitreLink: https://attack.mitre.org/wiki/Technique/T1053

to this:
MitreID: T1053.002
MitreLink: https://attack.mitre.org/techniques/T1053/002/

**Comment by wietze** [comment]
Good spot! I've included your suggestion in #170
