### ISSUE TITLE
dllhost /Processid:{xyz}

### ISSUE THREAD

**Issue by SpongeBobCodePants** [LOLBAS-Project/LOLBAS#114]
There is a technique listed here:

https://lolbas-project.github.io/lolbas/Binaries/Rundll32/

rundll32.exe -sta {CLSID}

but I don't see one for:

dllhost /Processid:{CLSID}

I've read the instructions for making a submission but figured I should ask if it makes sense to add this, lol. Thanks.

**Comment by wietze** [comment]
See #298 - closing this issue for now.
