### ISSUE TITLE
List of binary names

### ISSUE THREAD

**Issue by dancrossley** [LOLBAS-Project/LOLBAS#116]
I want to scrape just the list of binary names (eg 'schtasks.exe'). I can either scrape the list on the site or parse thru all the yml files. Is there a consolidated list that would make it easier? Thanks!

**Comment by wietze** [comment]
To my knowledge, no such list is maintained. As you indicated yourself, it is possible to dynamically generate the list based on the YAML files present in the the repository.

The following snippet should give you what you need:
```python3
>>> import glob, yaml
>>> [list(yaml.safe_load_all(open(file)))[0]['Name'] for file in glob.glob('yml/**/*.yml', recursive=True)]
['dnx.exe', 'Excel.exe', 'Dotnet.exe', 'Cdb.exe', 'Devtoolslauncher.exe', 'te.exe', ... ]
