### ISSUE TITLE
Userinit.exe backdoor

### ISSUE THREAD

**Issue by Ryan-OKeeffe** [LOLBAS-Project/LOLBAS#119]
Hello, userinit.exe which is built into Windows has been used in a living off the land attack (Astaroth). 

Astaroth attack:
https://securityintelligence.com/news/astaroth-attack-infects-windows-machines-via-living-off-the-land-techniques/

Backdoor installed with userinit.exe detected by Trend Micro.
https://www.trendmicro.com/vinfo/us/threat-encyclopedia/malware/Backdoor.Win32.SIMDA.C003X3KQ19/

**Comment by wietze** [comment]
The [Microsoft blog](https://www.microsoft.com/security/blog/2019/07/08/dismantling-a-fileless-campaign-microsoft-defender-atp-next-gen-protection-exposes-astaroth-attack/) linked to in the Security Intelligence article suggests a decrypted DLL is injected into a new `userinit.exe` instance. This does not meet the [criteria](https://github.com/LOLBAS-Project/LOLBAS#criteria) for LOLBAS. 

The registry key value `userinit` as described in step 4 of your Trend Micro link is one of the many Windows autostart locations, which in this modified by the backdoor (seems unrelated to Astaroth). This is not within LOLBAS's scope.

**Comment by Ryan-OKeeffe** [comment]
I see, thanks for the response and sorry for wasting time!
