### ISSUE TITLE
Add RdrLeakDiag.exe to LOLBAS project

### ISSUE THREAD

**Issue by tsamuels-r7** [LOLBAS-Project/LOLBAS#139]
The following method has been validated as a means to dump process memory. Please consider adding this native windows binary to the LOLBAS project.

rdrleakdiag.exe 

`C:\WINDOWS\system32>rdrleakdiag.exe /p <PID> /o <PATH> /fullmemdmp /snap`

_Originally posted by @tsamuels-r7 in https://github.com/LOLBAS-Project/LOLBAS/issues/84#issuecomment-852298997_

**Comment by bohops** [comment]
I believe I saw this one on Twitter.  Can you submit a PR?

https://github.com/LOLBAS-Project/LOLBAS/blob/master/CONTRIBUTING.md

**Comment by wietze** [comment]
I believe this was fixed with #216, closing this issue for now.
