### ISSUE TITLE
Add new LolBins

### ISSUE THREAD

**Issue by c0d3xpl0it** [LOLBAS-Project/LOLBAS#14]
***Missing Lolbins***

esentutl.exe (https://twitter.com/egre55/status/987037150108684288)

SystemSettings.exe (http://www.hexacorn.com/blog/2018/08/12/systemsettings-exe-yet-another-lolbin-for-loading-dlls/)

PrintDialog.exe (http://www.hexacorn.com/blog/2018/08/11/printdialog-exe-yet-another-lolbin-for-loading-dlls/)

**Comment by api0cradle** [comment]
Awesome. Will get these added. FTP.exe is in there.

**Comment by api0cradle** [comment]
Esentutl is there. The two other requires that you take a copy of the file into another folder and add a dll file. We have stated in our project that this does not qualify. 
Quote: DLL side-loading/hijacking without being relocated elsewhere in the filesystem.
ref: https://github.com/LOLBAS-Project/LOLBAS/blob/master/README.md
