### ISSUE TITLE
Investigate adding msinfo32.exe

### ISSUE THREAD

**Issue by ConsciousHacker** [LOLBAS-Project/LOLBAS#142]
Per @subtee on Twitter aka Casey Smith: https://twitter.com/subTee/status/1409919016504893452

`msinfo32 /nfo C:\path\lotsofinterestingthings.txt`

Not an lolbas :) .  May be should be classifed as recon?

No?

![image](https://user-images.githubusercontent.com/25334298/123852647-c7694580-d8d9-11eb-8e09-fb15b5e17497.png)

**Comment by TAbdiukov** [comment]
hmm. If `msinfo32` is added, then `dxdiag` will have to be on LOLBAS
