### ISSUE TITLE
Add taskmgr.exe to list

### ISSUE THREAD

**Issue by mgraf444** [LOLBAS-Project/LOLBAS#145]
Hello,

Can we have taskmgr.exe added to the list? Any reason for why it isn't already on the list. This is typically seen when the TA has GUI access to a windows device (example RDP session) and uses it to dump the lsass process.

**Comment by wietze** [comment]
Hey @mgraf444 , thanks for your suggestion. At this type, we have decided not to include GUI-based LOLBAS, see also https://github.com/LOLBAS-Project/LOLBAS/pull/177#issuecomment-1250180893. For this reason, I'm closing this issue now - if you have any questions, feel free to reply on this thread.
