### ISSUE TITLE
Add new function - Tamper

### ISSUE THREAD

**Issue by bohops** [LOLBAS-Project/LOLBAS#172]
'Tamper' is a function that better describes certain lolbin functionality. At least 2 lolbins are noted:

- fltmc.exe
- fsutil.exe (prospective)

There may be others.

**Comment by bohops** [comment]
Explore "uninstall security software" use case for msiexec.exe

**Comment by wietze** [comment]
Added 'tamper' and 'conceal' in LOLBAS-Project/LOLBAS-Project.github.io@d9405c164630633bbbe7332bb75e5595d8f8d2c0 . A category for uninstalling security software seems to be in line with 'Tamper'?  Closing this issue for now, feel free to reopen
