### ISSUE TITLE
Redundant/incorrect quotes in CL_LoadAssembly/UtilityFunction entries

### ISSUE THREAD

**Issue by oppiman** [LOLBAS-Project/LOLBAS#215]
First of all thank you all  for the great work.

CL_LoadAssembly.ps1 uses a wrong quote char at the first position, and there should be no quote anyway. At the end there is a quote char missing.

`”powershell.exe -command "set-location -path C:\Windows\diagnostics\system\Audio; import-module .\CL_LoadAssembly.ps1; LoadAssemblyFromPath ..\..\..\..\testing\fun.dll;[Program]::Fun()`

UtilityFunctions.ps1 uses a wrong quote char at the end.

`powershell.exe -command "set-location -path c:\windows\diagnostics\system\networking; import-module .\UtilityFunctions.ps1; RegSnapin ..\..\..\..\temp\unsigned.dll;[Program.Class]::Main()”`

Maybe better to use the HTML codes everywhere.

**Comment by wietze** [comment]
Thanks @oppiman, well spotted, you're right in both cases. Both issues were also identified in another pull request (#186) and have been fixed accordingly ([cl_loadassembly.ps1](https://github.com/LOLBAS-Project/LOLBAS/pull/186/files#diff-0eef12f167583ee7217d7c6601eaa118f49569f1fa006819fc51bb27ea7eee3c), [utilityfunctions.ps1](https://github.com/LOLBAS-Project/LOLBAS/pull/186/files#diff-ceb0d882aba26d4b14404ffa4184cc92a5344d3c5881b7e54bdc8a7d226a831f)). Hopefully this pull request gets merged soon.
