### ISSUE TITLE
Add conhost --headless example | Execute

### ISSUE THREAD

**Issue by bohops** [LOLBAS-Project/LOLBAS#248]
E.g. conhost.exe --headless notepad

![image](https://user-images.githubusercontent.com/21028609/189197480-3cd1f259-261b-4550-afad-4526ccf373ab.png)

Ref:
https://twitter.com/embee_research/status/1559410767564181504
https://twitter.com/ankit_anubhav/status/1561683123816972288

**Comment by bohops** [comment]
I think we just add a second example option. - it's a light lift so  I'll submit a PR.

**Comment by wietze** [comment]
Part of #263
