### ISSUE TITLE
winrs.exe - Probably should be on this list?

### ISSUE THREAD

**Issue by msftdevelop** [LOLBAS-Project/LOLBAS#304]
https://learn.microsoft.com/en-us/windows-server/administration/windows-commands/winrs

https://ss64.com/nt/winrs.html

https://jpcertcc.github.io/ToolAnalysisResultSheet/details/WinRS.htm

**Comment by wietze** [comment]
Hey @msftdevelop , thanks for the suggestion. As per the LOLBAS Project's [criteria](https://github.com/LOLBAS-Project/LOLBAS#criteria), candidate entries must be Microsoft signed, have 'unexpected' functionality, and should be useful to an attacker. Although the first and last conditions certainly apply to `winrm`, the links you provide do not appear to highlight any unexpected functionality. 

Therefore, if my assessment is right, this entry would unfortunately not be the right fit for this project. For that reason I'm closing this pull request now, if you think I'm wrong though please comment in here and I'll reopen the pull request.

<sub>For what it is worth, you are not the only one who thought `winrm` would be a useful addition - we have had similar suggestions  before(#51, #134).</sub>
