### ISSUE TITLE
[Question] downlaod with ftp.exe

### ISSUE THREAD

**Issue by noraj** [LOLBAS-Project/LOLBAS#31]
https://www.howtogeek.com/125447/stupid-geek-tricks-how-to-download-firefox-on-a-new-computer-without-using-internet-explorer/

Is there a way to non-interactively download a file with ftp.exe ?

**Comment by api0cradle** [comment]
Hi, you can script ftp.exe and do it that way.
Like this:
https://support.microsoft.com/en-us/help/555976
