### ISSUE TITLE
Typo on website

### ISSUE THREAD

**Issue by Luk164** [LOLBAS-Project/LOLBAS#316]
The main website has a typo in the word "arbitrary" - https://lolbas-project.github.io/functions/#:~:text=The%20LOLBAS%20can%20achieve%20abritrary%20code%20execution.

**Comment by wietze** [comment]
Thanks for letting us know, I just fixed the issue (https://github.com/LOLBAS-Project/LOLBAS-Project.github.io/pull/16) :+1:
