### ISSUE TITLE
Mshta ADS Execution

### ISSUE THREAD

**Issue by TheNaterz** [LOLBAS-Project/LOLBAS#35]
Was testing this out today, but wasn't able to get mshta to cooperate. If I inject an HTA into an ADS for some file "C:\ADS\file.txt"

`type bad.hta > C:\ADS\file.txt:bad.hta`

and try to execute with

`mshta.exe "C:\ADS\file.txt:bad.hta"`

I get a big white window, which I believe is an indication that mshta can't find the HTA. I'm currently testing on Version 1903. Do we know if mshta can still read from an ADS? Or am I missing something crucial?

**Comment by api0cradle** [comment]
You are right. This is not working anymore. Thanks for letting me know. Will update the entry in LOLBAS
