### ISSUE TITLE
[Addition] vssadmin is missing

### ISSUE THREAD

**Issue by p4yl0ad** [LOLBAS-Project/LOLBAS#395]
https://learn.microsoft.com/en-us/windows-server/administration/windows-commands/vssadmin
https://strontic.github.io/xcyclopedia/library/vssadmin.exe-2964D232005BD840B38F9DB4F95DC7DB.html

**Comment by wietze** [comment]
Hi @p4yl0ad , `vssadmin` certainly may be a useful executable in a living-off-the-land scenario, however, I'm not too sure whether it would meet our [criteria](https://github.com/LOLBAS-Project/LOLBAS?tab=readme-ov-file#criteria) of containing unexpected functionality. If you are aware of any, please feel free to submit a pull request.
