### ISSUE TITLE
Change yaml files to include categories

### ISSUE THREAD

**Issue by api0cradle** [LOLBAS-Project/LOLBAS#4]
Categories must be linked to the different commands. 
Example of a file that has multiple categories.
https://raw.githubusercontent.com/LOLBAS-Project/LOLBAS-Project.github.io/master/_lolbas/Binaries/Bitsadmin.md

**Comment by leesoh** [comment]
Do we have a master list of categories established yet, or do we need to build one?

**Comment by api0cradle** [comment]
Master list here:
https://github.com/LOLBAS-Project/LOLBAS/blob/master/CategoryList.md
