### ISSUE TITLE
Inaccurate privileges required

### ISSUE THREAD

**Issue by ConsciousHacker** [LOLBAS-Project/LOLBAS#41]
Regasm: "RegisterClass" requires local administrator, "UnRegisterClass" (regasm.exe /U) requires user level privileges.

https://lolbas-project.github.io/lolbas/Binaries/Regasm/

Regsvcs: "RegisterClass" requires local administrator, you cannot abuse Regsvcs with user level privileges as far as I know.

https://lolbas-project.github.io/lolbas/Binaries/Regsvcs/

Mostly creating this issue to remind myself to fix this as we're being referenced by MITRE and other reputable organizations.

**Comment by api0cradle** [comment]
regasm is done: https://github.com/LOLBAS-Project/LOLBAS/commit/d67c8f5c11b84ca971a4499420dae8883eccfdc2

**Comment by bohops** [comment]
Changed privilege level for regsvcs registration
