### ISSUE TITLE
Atbroker.exe incorrect regkey

### ISSUE THREAD

**Issue by secprentice** [LOLBAS-Project/LOLBAS#47]
The Detection section of the [Atbroker page](https://lolbas-project.github.io/lolbas/Binaries/Atbroker/) is incorrect.

It says: 

> Detection:
> Changes to HKCU\Software\Microsoft\Windows NT\CurrentVersion\Accessibility\Configuration
> **Changes to HKCU\Software\Microsoft\Windows NT\CurrentVersion\Accessibility\ATs**
> Unknown AT starting C:\Windows\System32\ATBroker.exe /start malware

This line is incorrect:

> Changes to HKCU\Software\Microsoft\Windows NT\CurrentVersion\Accessibility\ATs

Correct: 

> HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Accessibility\ATs

As per the [linked resources:](http://www.hexacorn.com/blog/2016/07/22/beyond-good-ol-run-key-part-42/)

> With Windows 8 Microsoft introduced a way to register third-party Assistive Technology applications on the system. All of them are stored inside the Registry under the following branch:
**HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Accessibility\ATs**

**Comment by api0cradle** [comment]
Thank you. this has now been corrected.
https://lolbas-project.github.io/lolbas/Binaries/Atbroker/
