### ISSUE TITLE
Add JJS.exe

### ISSUE THREAD

**Issue by api0cradle** [LOLBAS-Project/LOLBAS#65]
https://twitter.com/B_H101/status/1252138973847306241

**Comment by wietze** [comment]
@api0cradle `JJS.exe` appears to be part of the Oracle Java SDK (JDK), and is therefore not signed by Microsoft. This means the first rule within the [LOLBAS criteria](https://github.com/LOLBAS-Project/LOLBAS/blob/master/README.md#criteria) is not met. I'm closing this ticket for now, but please reopen if you disagree 🙂
