### ISSUE TITLE
Specific tags for specific capability caveats

### ISSUE THREAD

**Issue by api0cradle** [LOLBAS-Project/LOLBAS#9]
Specific tags/labeling for specific capability caveats, for example a App Whitelist bypass that works on AppLocker & Solidcore could cary tags for each product

**Comment by leesoh** [comment]
How would this differ from #4?

**Comment by api0cradle** [comment]
I am thinking this would require sub-cats or something. Would be nice to be able to see for instance which products that the AWL bypasses has been verified against. Guess we could just type it into the description.
